### ISSUE TITLE
Revisão 

### ISSUE THREAD

**Issue by mensonones** [petufc/sige#15]
**1 - apllication.properties**

**1.1:** Está sendo usado a propriedade: spring.datasource.driver-class-name=org.postgresql.Driver
Apesar de funcionar, pelo menos no Intellij ele marca o name como não resolvido a parte do postgresql. Uma dica: Não precisa colocar o name, pela url o spring subentende qual o SGBD. 
Ou usar: spring.datasource.platform=postgres

**1.2:** security.user.name e security.basic.enabled são deprecated. 
**Usar:** spring.security.user.name=user
      spring.security.user.password=password

**2 - Módulo Atividade**

**2.1:** Verificar o autoincremento do id da entidade atividade. Creio que falta: @Column(columnDefinition = "serial") 

**2.2:** Ainda na entidade atividade, será int mesmo no id? Creio que não é a melhor escolha. 

**2.3:** na atividade controller há um aviso em: private AtividadeService service;
O aviso é sobre ter mais de um bean do tipo AtividadeService. 
Atualmente é usado o AtividadeService, então qual a utilidade do AtividadeServiceImpl ?

Nos demais módulos apenas o mesmo já citado nos itens 2.1 e 2.2 e 2.3

**Comment by robsonsilv4** [comment]
**1.1** e **1.2** _done_

**Comment by mensonones** [comment]
Uma dica: Usar injeção de dependencia dentro do construtor.  
DI technique called Constructor-Based Dependency Injection within Spring
Ex:

@Autowired
	public AtividadeController(AtividadeService service){
		this.service = service;
	}

**Comment by robsonsilv4** [comment]
@mensonones eu estou utilizando @Service na interface e @Component na impl, foi a forma que encontrei para resolver um problema que estava tendo. Mas qual queria uma sugestão de melhor prática?
